config/routes.rb
StartIt::Application.routes.draw do

# =============================================================================
# Application Wide ============================================================
# =============================================================================
  root to: 'home#index'

  # User ======================================================================
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', 
                                    sessions: 'sessions', confirmations: 'confirmations' }
  devise_scope :user do
    get "users/sign_in", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "login", :to => "devise/sessions#new"
  end

  # Nav bar ===================================================================
  get 'create', to: 'explore#create'
  get 'build', to: 'explore#build'
  get 'buy', to: 'explore#buy'

  get 'terms', to: 'home#terms', as: 'terms'
  get 'privacy', to: 'home#privacy', as: 'privacy'  

# =============================================================================
# Phase 1 =====================================================================
# =============================================================================

  match "/comments/vote", via:[:post], as: "comment_vote"
  match "/questions/vote", via:[:post], as: "question_vote"
  match "/answers/vote", via:[:post], as: "answer_vote"
  match "/ideas/vote", via:[:post], as: "idea_vote"
  match "/solutions/vote", via:[:post], as: "solution_vote"
  
  get "evaluations/show"

  #get "/dashboard", to: 'home#dashboard', as: 'dashboard'

  resources :notifications, only: [:index, :destroy]
  resources :profiles, except: [:index, :new, :create]
  resources :idea_relationships, only: [:create, :destroy]
  resources :comments, only: [:show]
  resources :questions, except: [:index, :create, :update]
  resources :answers, except: [:index, :create]
  resources :aspects, except: [:index, :show, :create, :new] do
    resources :solutions, except: [:index, :edit, :update, :create, :show, :new]
  end

  resources :ideas do
    member do
      post :vote 
      get :followers
    end
    resources :idea_build, only: [:edit, :clear, :update] # This is phase 2
  end

  get '/solutions/:id', to: 'solutions#show', as: 'solution'
  post '/ideas/:idea_id/aspects/:id/solution/create', to: 'solutions#create', as: 'create_solution'

  get '/ideas/:id/questions/new', to: 'ideas#new_question', as: 'idea_new_question'
  get '/ideas/:id/questions/:question_id', to: 'ideas#edit_question', as: 'idea_edit_question'
  post '/ideas/:id/questions/', to: 'questions#create', as: 'create_question'
  patch '/ideas/:id/questions/:question_id', to: 'questions#update', as: 'update_question'
  post '/ideas/:id/questions/:question_id', to: 'answers#create', as: 'create_answer'
  post "/ideas/:idea_id/:commentable_type/:commentable_id", to: 'comments#create', as: 'create_comment'

  get '/ideas/:idea_id/aspects/:id', to: 'aspects#show', as: 'idea_aspect'

  get '/ideas/:id/define', to: 'ideas#define'
  get '/ideas/:id/reputation', to: 'ideas#reputation', as: 'reputation_path'
  get '/ideas/:id/activity', to: 'ideas#activity'

  get '/profiles/:id/skills', to: 'profiles#skills'
  get "profile", :to => "profiles#show"
  
  get "activities/index"
  get "/followed_ideas", to: 'home#followed_ideas', as: 'followed_ideas'

  post 'ideas/:id/increase_create_length', to: 'ideas#increase_create_length', as: 'increase_create_length'

# =============================================================================
# Phase 2 =====================================================================
# =============================================================================

=begin
  get 'build_needs_team', to: 'explore#needs_team'
  get 'documentation', to: 'home#documentation'

  get "/ideas/:idea_id/parts/:id/edit", to: "parts#edit", as: "edit_part"
  get "/ideas/:idea_id/parts/:id/help_content", to: "parts#help_content", as: "part_help_content"
  get '/download', to: 'parts#download', as: 'download'
  get "/ideas/:idea_id/parts/:id/admin_tasks", to: "parts#admin_tasks", as: "part_admin_tasks"
  put "/ideas/:idea_id/parts/:id/update", to: "parts#update", as: "update_part"
  put "/ideas/:idea_id/parts/:id/update_image", to: "parts#update_image", as: "update_image_part"
  put "/ideas/:idea_id/parts/:id/add_user_to_repo", to: "parts#add_user_to_repo", as: "add_user_to_repo"
  put "/ideas/:idea_id/parts/:id/unstart_part", to: "parts#unstart_part", as: "unstart_part"
  post "/ideas/:idea_id/parts/:id/update_status", to: "parts#update_status", as: "update_status"
  delete "/ideas/:idea_id/parts/:id/clear", to: "parts#clear", as: "clear_part"
  delete "/ideas/:idea_id/parts/:id/edit/remove_upload/:upload_id", to:"part_upload#destroy", as: "destroy_upload"
  delete "/ideas/:idea_id/parts/:id/remove_user", to: "parts#remove_user_from_repo", as: "remove_user_from_repo"
  
  get '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#new', as: 'new_admin_task'
  post '/ideas/:idea_id/parts/:part_id/admin_tasks/:id/update_status', to: 'admin_tasks#update_status', as: 'update_admin_task'
  post '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#create', as: 'create_admin_task'

  post '/ideas/:idea_id/idea_build/:kind/:kind_id/comments/create', to: 'task_comments#create', as: 'create_task_comment'

  get "/ideas/:idea_id/build", to: "idea_builds#overview", as: 'idea_build'
  get "/ideas/:idea_id/overview/news_feed", to: 'idea_builds#news_feed', as: 'idea_build_feed'
  get "/ideas/:idea_id/overview/team_build", to: 'idea_builds#team_build', as: 'idea_build_team_build'
  get "/ideas/:idea_id/discussion", to: 'idea_builds#discussion', as: 'idea_build_discussion'
  post "/ideas/:idea_id/overview/news_feed/create_post", to: 'posts#create', as: 'create_post'
  post "/ideas/:idea_id/overview/team_build/create_proposal", to: 'posts#create_proposal', as: 'create_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/close_proposal", to: 'posts#close_proposal', as: 'close_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/apply", to: 'team_applications#create', as: 'create_team_application'
  get "/ideas/:idea_id/overview/team_build/proposals/:post_id/", to: 'posts#show', as: 'post'
  get '/ideas/:idea_id/:kind/:kind_id/discussion', to: 'chats#new', as: 'new_chat'
  post '/ideas/:idea_id/:kind/:kind_id/create_chat', to: 'chats#create', as: 'create_chat'
  get '/ideas/:idea_id/:kind/:kind_id/chats', to: 'chats#index', as: 'chats'

  get "/ideas/:idea_id/build/components", to: "idea_builds#components", as: 'idea_build_components'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  post 'like/:model_name/:model_id/:user_id', to: 'likes#like', as: 'like'
  delete 'like/:model_name/:model_id/:user_id', to: 'likes#unlike', as: 'unlike'

  post '/strike/:user_id/:idea_build_id/:voter_id', to: 'strike#create', as: 'strike'  

  post '/ideas/:idea_build_id/team_applications/:team_application_id', to: 'team_memberships#create', as: 'create_team_member'

# =============================================================================
# Phase 3 =====================================================================
# =============================================================================

  post '/buy/:id/buy', to: 'buy_phase_vote#buy_vote', as: 'buy_vote'
  post '/buy/:id/use', to: 'buy_phase_vote#use_vote', as: 'use_vote'
=end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :auth_user!, only: [:index, :terms, :privacy]
  
  def index
    return redirect_to create_path unless current_user.nil?

    render layout: 'sidebar_signup'
  end

  def dashboard
  	@user_activities   = PublicActivity::Activity.includes(:owner, :trackable).where(owner: current_user).order("created_at desc").take(20)
    @follow_activities = current_user.get_followed_idea_activity

    render layout: 'sidebar_right'
  end

  def followed_ideas
    @user_activities   = PublicActivity::Activity.includes(:owner, :trackable).where(owner: current_user).order("created_at desc").take(20)
    @follow_activities = current_user.get_followed_idea_activity

    render layout: 'sidebar_right'
  end
  
  def documentation
  end

  def terms
  end

  def privacy
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_secondary_nav.html.erb
<% content_for :secondary_nav do %> 
  <div class="secondary-nav">
    <% if current_page?("/") %>
      <div style='float:left; height:40px; display:none;' id='2-div'>
        <a id="2-pop-link" 
             href="#" 
             data-toggle="popover"
             data-html="true" 
             data-content="<b>My Activity</b> shows you all of your most recent contributions to ideas in all phases. For example, it will list questions you've contributed to ideas in the <b>create</b> phase, or parts that you've started in the <b>build</b> phase. <b>My Followed Ideas Activity</b> shows you the most recent contributions submitted by all users to the ideas that you follow in all phases. It is akin to the <b>Activity</b> tab on an idea's create page.<br><br><b>My Followed Ideas</b> shows you a list of the ideas you follow along with your local reputation and equity in each of them.">
          <%= image_tag 'labthinghelp.png', size: '36x36', id: '2-img' %>
          <span id='2-close' class='pull-left' style='display:none; position:absolute; top:0; margin-left:-5px; color:#34495E;'>
           <b>x</b>
          </span>
        </a>      
      </div>
    <% end %>
    <%= link_to "My Activity", '/',
      class: 'btn btn-default ' + active_when(:controller => 'home', :action => 'dashboard')
    %>
    <%= link_to "My Followed Ideas Activity", '/followed_ideas',
      class: 'btn btn-default ' + active_when(:controller => 'home', :action => 'followed_ideas')
    %>
<% end %>

<% content_for :sidebar_right do %>
  <h4 style='font-family: "Montserrat" !important;'>My Followed Ideas</h4>
  <%= render 'users/followed_ideas', user: current_user %>
<% end %>

app/views/home/dashboard.html.erb
<%= render 'secondary_nav' %>
<h4 style='font-family: "Montserrat" !important;'>My Recent Activity</h4>
<%= render partial: "activities/activities", :locals => {activities: @user_activities} %>
<br><br>

app/views/home/followed_ideas.html.erb
<%= render 'secondary_nav' %>
<div class='partname'>
<h4 style='font-family: "Montserrat" !important;'>Recent Activity From My Followed Ideas</h4>
<%= render partial: "activities/activities", :locals => {activities: @follow_activities} %>
</div>
<br><br>

app/views/home/index.html.erb
<h1 class='heading' style="font-size:5em; color:#fff;font-family:'Montserrat"><strong> Big Ideas. Come Play.</strong></h1><br>
<br>
<div class='col-md-2 no-gutter'>
<img src='images/lightbulb.png' alt='LabthingGuy' class='create-icon chart-icon pull-left' style='height:130px;margin-top:10px;float:left;'>
</div>
<div class='col-md-10'><h2 class='subheading' style='line-height: 1.1; letter-spacing: -1px; color: #fff;'>
  <p class='doc'>Collaborate with university students from all over the world to turn your big idea into a profitable business. We help you build your start-up, obtain funding, and create success.</p>
</h2></div>


<% content_for :sidebar_signup do %>
  <div id='register' >
	 <% title = "" %>
	 <%= render template: 'devise/registrations/new', locals: {title: title} %>
  </div>
  <div id='login' style='display:none; margin-top:-5px;'>
   <%= render template: 'devise/sessions/new' %>
  </div>
<% end %>

app/views/home/privacy.html.erb
<h2 class='set-font-bold'>Internet Privacy and Cookies Policy</h2>

<p>At Labthi.ng we are committed to safeguarding and preserving the privacy of our visitors. This Privacy Policy document (the "Policy") has been provided by the legal resource <%= link_to 'DIY Legals', 'http://www.diylegals.co.uk/ecommerce/website-privacy-policy/' %> and reviewed and approved by their solicitors.</p>

<p>This Policy explains what happens to any personal data that you provide to us, or that we collect from you whilst you visit our site and how we use cookies on this website.
We do update this Policy from time to time so please do review this Policy regularly.</p>

<h3 class='set-font-bold'>Information That We Collect</h3><hr>
<p>In running and maintaining our website we may collect and process the following data about you:
Information about your use of our site including details of your visits such as pages viewed and the resources that you access. Such information includes traffic data, location data and other communication data.
Information provided voluntarily by you. For example, when you register for information or make a purchase.
Information that you provide when you communicate with us by any means.</p>

<h3 class='set-font-bold'>Use of Cookies</h3><hr>
<p>Cookies provide information regarding the computer used by a visitor. We may use cookies where appropriate to gather information about your computer in order to assist us in improving our website.
We may gather information about your general internet use by using the cookie. Where used, these cookies are downloaded to your computer and stored on the computer’s hard drive. Such information will not identify you personally; it is statistical data which does not identify any personal details whatsoever.</p>
<p>You can adjust the settings on your computer to decline any cookies if you wish. This can be done within the “settings” section of your computer. For more information please read the advice at AboutCookies.org. Disabling cookies will mean you are unable to remain logged into our site as our authentication system relies on them.</p>

<h3 class='set-font-bold'>Use of Your Information</h3><hr>
<p>We use the information that we collect from you to provide our services to you. In addition to this we may use the information for one or more of the following purposes:<br>
To provide information to you that you request from us relating to our products or services.
To provide information to you relating to other products that may be of interest to you. Such additional information will only be provided where you have consented to receive such information.
To inform you of any changes to our website, services or goods and products.
If you have previously purchased goods or services from us we may provide to you details of similar goods or services, or other goods and services, that you may be interested in.
We never give your details to third parties to use your data to enable them to provide you with information regarding unrelated goods or services.</p>

<h3 class='set-font-bold'>Storing Your Personal Data</h3><hr>
<p>In operating our website it may become necessary to transfer data that we collect from you to locations outside of the European Union for processing and storing. By providing your personal data to us, you agree to this transfer, storing and processing. We do our utmost to ensure that all reasonable steps are taken to make sure that your data is stored securely.
Unfortunately the sending of information via the internet is not totally secure and on occasion such information can be intercepted. We cannot guarantee the security of data that you choose to send us electronically, sending such information is entirely at your own risk.</p>

<h3 class='set-font-bold'>Disclosing Your Information</h3><hr>
<p>We will not disclose your personal information to any other party other than in accordance with this Privacy Policy and in the circumstances detailed below:<br>
In the event that we sell any or all of our business to the buyer.
Where we are legally required by law to disclose your personal information.
To further fraud protection and reduce the risk of fraud.</p>

<h3 class='set-font-bold'>Third Party Links</h3><hr>
<p>On occasion we include links to third parties on this website. Where we provide a link it does not mean that we endorse or approve that site’s policy towards visitor privacy. You should review their privacy policy before sending them any personal data.</p>

<h3 class='set-font-bold'>Access to Information</h3><hr>
<p>In accordance with the Data Protection Act 1998 you have the right to access any information that we hold relating to you. Please note that we reserve the right to charge a fee of £10 to cover costs incurred by us in providing you with the information.</p>

<h3 class='set-font-bold'>Contacting Us</h3><hr>
<p>Please do not hesitate to contact us regarding any matter relating to this Privacy and Cookies Policy via email at labthing@gmail.com.</p>
</div></div>

<div class='footer' style='margin-bottom:-700px;'>
  <div class='container' style-'height:40px !important;'>
    <div class='col-md-12' style='margin-top:-10px;'>
        <span class='p-footer pull-left'>Questions? Comments? We want your input. <a class='email-footer' href="mailto:labthingco@gmail.com?Subject=Hi%20Labthi.ng!" target="_top" style='color:#fff !important;'><b>Contact us!</b></a> | <b><%= link_to 'Terms & Conditions', terms_path, style: 'color:#fff !important;', class: 'set-font-bold' %></b> | <b><%= link_to 'Privacy Policy', privacy_path, style: 'color:#fff !important;', class: 'set-font-bold'%></b> </span>
        <span class='p-footer copy pull-right'>© Labthi.ng Ltd.</span>
    </div>
  </div>
</div>
</body>
</html>

app/views/home/terms.html.erb
<h2 class='set-font-bold'>Terms of Serive for Labthi.ng</h2>
<hr>
<h3 class='set-font-bold'>Definitions</h3>
<p class='terms'>"Account" refers to the users account for the Service.<br>
"Third Party" means any third party (i) to which You provide access to Your Account or (ii) for which You use the Service to collect information on the third party's behalf.<br>
“Labthi.ng” refers to the company Labthi.ng with corpaoration code: 1234567890<br>
“Member Content” refers to any content submitted by a member to any other content on the labthi.ng web platform. <br>
“Confidential Information” refers to any content related to an idea.<p>
<hr>
<h3 class='set-font-bold'>Acceptance of Terms Clause</h3><hr>
By accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using any of this websites particular services, you shall be subject to any posted guidelines or rules applicable to such services, which may be posted and modified from time to time. All such guidelines or rules are hereby incorporated by reference into the Terms and Conditions.<br><br>
ANY PARTICIPATION IN THIS SITE WILL CONSTITUTE ACCEPTANCE OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ABIDE BY THE ABOVE, DO NOT USE THIS SITE.<br><br>
<h3 class='set-font-bold'>Ownership of Ideas</h3><hr>
By submitting an idea to Labthi.ng, you temporarily transfer your intellectual property rights to Labthi.ng until incorporation. This is to ensure all forms of legal protection of your idea.

<h3 class='set-font-bold'>Fees and Service</h3><hr>
<p class='terms'>This Service is provided to you free of charge in phases 1 and 2. To progress from phase 2 to phase 3 the team will have to pay a £15 incorporation fee within 30 days. Once paid the team will have a chance to submit a proposal for dividing the equity within 30 days after payment. Labthin.ng will have a non negotiable, non dialutable 5% share holding in the company and will have final say on any agreement. If you do not pay the £15 fee within 30 days the business will be incorporated and Labthi.ng will be the sole owner, including all work product and intellectual property. If you fail to come to an agreement on splitting the equity within 30 days, all team members will evenly divide the remaining 95% of equity. <br>There are no other charges for the use of the service.</p>

<h3 class='set-font-bold'>Confidentiality</h3><hr>
<p class='terms'>BY SUBMITTING, VOTING ON OR OTHERWISE ACCESSING AN IDEA IN ANY OF THE THREE PHASES, YOU ACKNOWLEDGE AND AGREE THAT ALL INFORMATION DISCLOSED VIA LABTHI.NG AND OTHER MEMBERS THAT RELATES TO SUCH IDEAS, WHETHER SUCH INFORMATION IS IDENTIFIED AS SUCH, IS PROPRIETARY OR CONFIDENTIAL INFORMATION OF LABTHI.NG (“CONFIDENTIAL INFORMATION”). YOU SHALL NOT DISCLOSE ANY CONFIDENTIAL INFORMATION TO ANY PERSON OR ENTITY, OTHER THAN MEMBERS OF THE LABTHI.NG COMMUNITY, OR USE CONFIDENTIAL INFORMATION EXCEPT TO AID IN THE DEVELOPMENT OF IDEAS ON LABTHI.NG.
“Confidential Information” does not include information that demonstrably (i) is or becomes generally available to the public other than as a result of disclosure by you; or (ii) the Idea has been published or otherwise made available to the general public by Labthi.ng.</p>

<h3 class='set-font-bold'>Limiting Liability</h3><hr>
<p class='terms'>This site and its components are offered for informational purposes only; this site shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted or made available via the site, and shall not be responsible or liable for any error or omissions in that information.
TO THE EXTENT PERMITTED BY APPLICABLE LAW, LABTHI.NG WILL NOT BE LIABLE FOR YOUR LOST REVENUES OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, EVEN IF THE LABTHI.NG HAS BEEN ADVISED OF, KNEW OR SHOULD HAVE KNOWN THAT SUCH DAMAGES WERE POSSIBLE AND EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY. LABTHI.NG’S TOTAL CUMULATIVE LIABILITY TO YOU OR ANY OTHER PARTY FOR ANY LOSS OR DAMAGES RESULTING FROM CLAIMS, DEMANDS, OR ACTIONS ARISING OUT OF OR RELATING TO THIS AGREEMENT WILL NOT EXCEED £0 (GBP).</p>

<h3 class='set-font-bold'>Eligibility</h3>

<p class='terms'>Participation in the Site is void where prohibited. This Site is intended solely for users who are eighteen (18) years of age or older. Any registration by, use of or access to the Site by anyone under 18 is unauthorized, unlicensed and in violation of these Terms of Use. By using the Services or the Site, you represent and warrant that you are 18 or older, and that you agree to and will abide by all of the terms and conditions of this Agreement. If you are entering into this agreement on behalf of a third party, you represent that you have the authority to enter into his Agreement on the third parties behalf, and to bind it to the terms of this Agreement.</p>

<h3 class='set-font-bold'>Member Account, Password and Security</h3><hr>
<p class='terms'>To register for the Service, You must complete the registration process by providing Labthi.ng with current, complete and accurate information as prompted by the registration form, including Your e-mail address (username) and password. You will protect Your passwords and take full responsibility for Your own, and third party, use of Your accounts. You are solely responsible for any and all activities that occur under Your Account. You will notify Labthi.ng immediately upon learning of any unauthorized use of Your Account or any other breach of security by emailing security@labthi.ng. Labthi.ng support staff may, from time to time, log in to the Service under Your customer password in order to maintain or improve service, including to provide You assistance with technical issues.</p>

<h3 class='set-font-bold'>Member Removal From an Idea</h3>

<p class='terms'>We have implemented a democratic strike system. If all members in a team excluding you vote to give you a strike you will receive an additional one in that idea. Once you receive 3 strikes in an idea you will be removed from it and give up all work product and rights to that idea. </p>

<h3 class='set-font-bold'>Media Waiver</h3><hr>
<p class='terms'>You agree that Labthi.ng has the absolute right and permission to use your name, voice, image, likeness, and your applicable Member account information, including for example any equity holding in companies, as well as representations made by you, in any media (including, without limitation, television, print, radio and the Internet), world-wide, for the purposes of advertising, promoting, reporting and disseminating information about the Company, the Company’s business or a Product.</p>

<h3 class='set-font-bold'>Monitoring Member Content</h3><hr>

<p class='terms'>Labthi.ng is not responsible or liable in any manner for any Member Content posted on the Site or in connection with the Services. We do not control and are not responsible for what Members post, transmit or share on the Site and are not responsible for any offensive, inappropriate, obscene, unlawful or otherwise objectionable Site Content you may encounter on the Site or in connection with any Member Content. The Company is not responsible for the conduct, whether online or offline, of any Member of the Site or Services.</p>

<h3 class='set-font-bold'>Service Interruptions or Site Changes</h3>

<p class='terms'>Labthi.ng reserves the right to interrupt the Site with or without prior notice for any reason or no reason. You agree that Labthi.ng will not be liable for any interruption of the Site, delay or failure to perform. Labthi.ng has the right at any time for any reason or no reason to change and/or eliminate any aspect(s) of the Site and/or the Services as it sees fit in its sole discretion.</p>

<h3 class='set-font-bold'>Warranty Disclaimers</h3><hr>
<p class='terms'>WITHOUT LIMITING THE FOREGOING, THE SITE CONTENT, SERVICES AND ALL OTHER FEATURES ON THE SITE ARE PROVIDED TO YOU “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTY OF ANY KIND WITH RESPECT TO THE SITE AND/OR SERVICES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT. ADDITIONALLY, COMPANY DOES NOT MAKE ANY WARRANTIES THAT THE SITE OR SERVICES WILL BE UNINTERRUPTED, SECURE OR ERROR FREE OR THAT YOUR USE OF THE SITE WILL MEET YOUR EXPECTATIONS, OR THAT THE SITE, SERVICES, OR ANY PORTION THEREOF, IS CORRECT, ACCURATE, OR RELIABLE. COMPANY RESERVES THE RIGHT TO CHANGE ANY PART OF THE SITE AT ANYTIME WITHOUT NOTICE. YOUR USE OF THE SITE AND SERVICES IS AT YOUR OWN RISK.</p>

<h3 class='set-font-bold'>Indemnification</h3><hr>
<p class='terms'>You hereby agree to defend, indemnify and hold harmless Labthi.ng, its shareholders, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, licensees, distributors, successors and assigns and other Members of the Services, from all damages, liabilities, claims and expenses, including without limitation attorneys' fees and costs, arising from (i) any breach of this Agreement by you, or (ii) any claims by third parties that your activity on the Site or your Member Content (including your Member Content as incorporated in a Software Product) infringes upon, violates or misappropriates any of their Intellectual Property Rights or discloses their Proprietary Information.</p>

<h3 class='set-font-bold'>No Archive</h3><hr>
<p class='terms'>Notwithstanding anything contained herein, the functionality provided to you by the Site, Services and the Company’s systems, networks, and servers are not an archive and Company shall have no liability to you or any other person for loss, damage or destruction to your Member Content or any other information submitted to or via the Site. You shall be solely responsible for (i) uploading your Member Content, (ii) preventing any loss or damage to your Member Content and (iii) maintaining independent archival and backup copies of any of your Member Content.</p>

<h3 class='set-font-bold'>Modification of Terms of Service</h3><hr>
<p class='terms'>Labthi.ng may modify these terms or any additional terms that apply to the Service to, for example, reflect changes to the law or changes to the Service. You should look at the terms regularly. Labthi.ng will notify you by email to your registered address of modifications to these terms or policies referenced in these terms at the applicable URL for such policies. Changes will not apply retroactively and will become effective no sooner than 14 days after they are posted. If You do not agree to the modified terms for the Service, You should discontinue Your use Labthi.ng by clicking the appropriate link in the email sent to you.</p>

<h3 class='set-font-bold'>Termination</h3><hr>
<p class='terms'>Company may cancel, suspend or block your use of the Site without notice if there has been a violation of these Terms. Labthi.ng reserves the right to terminate this Agreement with you if you do not, in any 12-month period, log in to (and update, if necessary) your account. If this Agreement is terminated by you or by Labthi.ng due to your breach or as provided in the previous sentence, your Stake in any Idea will be forfeit. Your right to use the Site will end once your Member account is terminated, and any data you have stored on the Site, may be unavailable later. You may terminate your Member account at any time. Company is not responsible or liable for any records or information that is made unavailable to you as the result of your termination of your Member account.</p><br><br>
YOU AGREE THAT COMPANY WILL NOT BE LIABLE TO YOU OR ANY OTHER PARTY FOR ANY TERMINATION OF YOUR ACCESS TO THE SITE, CONTENT OR MATERIALS.<br><br>
Any limitations on liability that favor Company will survive the expiration or termination of these Terms for any reason.
</div>
</div>

<div class='footer' style='margin-bottom:-2500px;'>
  <div class='container' style-'height:40px !important;'>
    <div class='col-md-12' style='margin-top:-10px;'>
        <span class='p-footer pull-left'>Questions? Comments? We want your input. <a class='email-footer' href="mailto:labthingco@gmail.com?Subject=Hi%20Labthi.ng!" target="_top" style='color:#fff !important;'><b>Contact us!</b></a> | <b><%= link_to 'Terms & Conditions', terms_path, style: 'color:#fff !important;', class: 'set-font-bold' %></b> | <b><%= link_to 'Privacy Policy', privacy_path, style: 'color:#fff !important;', class: 'set-font-bold'%></b> </span>
        <span class='p-footer copy pull-right'>© Labthi.ng Ltd.</span>
    </div>
  </div>
</div>
</body>
</html>