config/routes.rb
StartIt::Application.routes.draw do

# =============================================================================
# Application Wide ============================================================
# =============================================================================
  root to: 'home#index'

  # User ======================================================================
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', 
                                    sessions: 'sessions', confirmations: 'confirmations' }
  devise_scope :user do
    get "users/sign_in", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "login", :to => "devise/sessions#new"
  end

  # Nav bar ===================================================================
  get 'create', to: 'explore#create'
  get 'build', to: 'explore#build'
  get 'buy', to: 'explore#buy'

  get 'terms', to: 'home#terms', as: 'terms'
  get 'privacy', to: 'home#privacy', as: 'privacy'  

# =============================================================================
# Phase 1 =====================================================================
# =============================================================================

  match "/comments/vote", via:[:post], as: "comment_vote"
  match "/questions/vote", via:[:post], as: "question_vote"
  match "/answers/vote", via:[:post], as: "answer_vote"
  match "/ideas/vote", via:[:post], as: "idea_vote"
  match "/solutions/vote", via:[:post], as: "solution_vote"
  
  get "evaluations/show"

  #get "/dashboard", to: 'home#dashboard', as: 'dashboard'

  resources :notifications, only: [:index, :destroy]
  resources :profiles, except: [:index, :new, :create]
  resources :idea_relationships, only: [:create, :destroy]
  resources :comments, only: [:show]
  resources :questions, except: [:index, :create, :update]
  resources :answers, except: [:index, :create]
  resources :aspects, except: [:index, :show, :create, :new] do
    resources :solutions, except: [:index, :edit, :update, :create, :show, :new]
  end

  resources :ideas do
    member do
      post :vote 
      get :followers
    end
    resources :idea_build, only: [:edit, :clear, :update] # This is phase 2
  end

  get '/solutions/:id', to: 'solutions#show', as: 'solution'
  post '/ideas/:idea_id/aspects/:id/solution/create', to: 'solutions#create', as: 'create_solution'

  get '/ideas/:id/questions/new', to: 'ideas#new_question', as: 'idea_new_question'
  get '/ideas/:id/questions/:question_id', to: 'ideas#edit_question', as: 'idea_edit_question'
  post '/ideas/:id/questions/', to: 'questions#create', as: 'create_question'
  patch '/ideas/:id/questions/:question_id', to: 'questions#update', as: 'update_question'
  post '/ideas/:id/questions/:question_id', to: 'answers#create', as: 'create_answer'
  post "/ideas/:idea_id/:commentable_type/:commentable_id", to: 'comments#create', as: 'create_comment'

  get '/ideas/:idea_id/aspects/:id', to: 'aspects#show', as: 'idea_aspect'

  get '/ideas/:id/define', to: 'ideas#define'
  get '/ideas/:id/reputation', to: 'ideas#reputation', as: 'reputation_path'
  get '/ideas/:id/activity', to: 'ideas#activity'

  get '/profiles/:id/skills', to: 'profiles#skills'
  get "profile", :to => "profiles#show"
  
  get "activities/index"
  get "/followed_ideas", to: 'home#followed_ideas', as: 'followed_ideas'

  post 'ideas/:id/increase_create_length', to: 'ideas#increase_create_length', as: 'increase_create_length'

# =============================================================================
# Phase 2 =====================================================================
# =============================================================================

=begin
  get 'build_needs_team', to: 'explore#needs_team'
  get 'documentation', to: 'home#documentation'

  get "/ideas/:idea_id/parts/:id/edit", to: "parts#edit", as: "edit_part"
  get "/ideas/:idea_id/parts/:id/help_content", to: "parts#help_content", as: "part_help_content"
  get '/download', to: 'parts#download', as: 'download'
  get "/ideas/:idea_id/parts/:id/admin_tasks", to: "parts#admin_tasks", as: "part_admin_tasks"
  put "/ideas/:idea_id/parts/:id/update", to: "parts#update", as: "update_part"
  put "/ideas/:idea_id/parts/:id/update_image", to: "parts#update_image", as: "update_image_part"
  put "/ideas/:idea_id/parts/:id/add_user_to_repo", to: "parts#add_user_to_repo", as: "add_user_to_repo"
  put "/ideas/:idea_id/parts/:id/unstart_part", to: "parts#unstart_part", as: "unstart_part"
  post "/ideas/:idea_id/parts/:id/update_status", to: "parts#update_status", as: "update_status"
  delete "/ideas/:idea_id/parts/:id/clear", to: "parts#clear", as: "clear_part"
  delete "/ideas/:idea_id/parts/:id/edit/remove_upload/:upload_id", to:"part_upload#destroy", as: "destroy_upload"
  delete "/ideas/:idea_id/parts/:id/remove_user", to: "parts#remove_user_from_repo", as: "remove_user_from_repo"
  
  get '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#new', as: 'new_admin_task'
  post '/ideas/:idea_id/parts/:part_id/admin_tasks/:id/update_status', to: 'admin_tasks#update_status', as: 'update_admin_task'
  post '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#create', as: 'create_admin_task'

  post '/ideas/:idea_id/idea_build/:kind/:kind_id/comments/create', to: 'task_comments#create', as: 'create_task_comment'

  get "/ideas/:idea_id/build", to: "idea_builds#overview", as: 'idea_build'
  get "/ideas/:idea_id/overview/news_feed", to: 'idea_builds#news_feed', as: 'idea_build_feed'
  get "/ideas/:idea_id/overview/team_build", to: 'idea_builds#team_build', as: 'idea_build_team_build'
  get "/ideas/:idea_id/discussion", to: 'idea_builds#discussion', as: 'idea_build_discussion'
  post "/ideas/:idea_id/overview/news_feed/create_post", to: 'posts#create', as: 'create_post'
  post "/ideas/:idea_id/overview/team_build/create_proposal", to: 'posts#create_proposal', as: 'create_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/close_proposal", to: 'posts#close_proposal', as: 'close_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/apply", to: 'team_applications#create', as: 'create_team_application'
  get "/ideas/:idea_id/overview/team_build/proposals/:post_id/", to: 'posts#show', as: 'post'
  get '/ideas/:idea_id/:kind/:kind_id/discussion', to: 'chats#new', as: 'new_chat'
  post '/ideas/:idea_id/:kind/:kind_id/create_chat', to: 'chats#create', as: 'create_chat'
  get '/ideas/:idea_id/:kind/:kind_id/chats', to: 'chats#index', as: 'chats'

  get "/ideas/:idea_id/build/components", to: "idea_builds#components", as: 'idea_build_components'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  post 'like/:model_name/:model_id/:user_id', to: 'likes#like', as: 'like'
  delete 'like/:model_name/:model_id/:user_id', to: 'likes#unlike', as: 'unlike'

  post '/strike/:user_id/:idea_build_id/:voter_id', to: 'strike#create', as: 'strike'  

  post '/ideas/:idea_build_id/team_applications/:team_application_id', to: 'team_memberships#create', as: 'create_team_member'

# =============================================================================
# Phase 3 =====================================================================
# =============================================================================

  post '/buy/:id/buy', to: 'buy_phase_vote#buy_vote', as: 'buy_vote'
  post '/buy/:id/use', to: 'buy_phase_vote#use_vote', as: 'use_vote'
=end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include PublicActivity::Model
  include LabReputable
  after_create :add_first_vote
  after_create :create_notification
  validates :brief, presence: true, length: { maximum: 1000 }
  validates :user, presence: true
  validates :question, presence: true
  belongs_to :question, inverse_of: :answers
  belongs_to :user, -> { includes :profile }, inverse_of: :answers
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :notifications

  def ids
    [['Answer', self.id]]
  end

  def Answer.user_stats(idea, user)
    questions = Question.where(idea_id: idea.id)
    count     = 0
    questions.each do |q|
      count += Answer.where(question_id: q.id, user_id: user.id).length
    end
    count
  end

  private
    def create_notification
      Notification.create(self.question, self.id, 'question_answer')
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_question, only: [:new]
  before_action :set_vote_value, only: [:vote]

  # GET /answers/1
  # GET /answers/1.json
  def show
    redirect_to @answer.question
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        @answer.create_activity :create, owner: (current_user)
        format.html { redirect_to @answer.question, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
        #format.js {render template: 'answers/create'}
        if not current_user.following_idea?(@answer.question.idea)
          current_user.follow_idea!(@answer.question.idea)
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        @answer.create_activity :update, owner: (current_user)
        format.html { redirect_to @answer.question, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  def vote
    @voteable = Answer.find(params[:voteable_id])
    @voteable.update_lab_evaluation(@value, current_user) unless current_user == nil
    respond_to do |format|
      format.html {redirect_to :back, notice: "Vote submitted"}
      format.js {render template: 'evaluations/vote'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:brief, :user_id, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<% # This template is called from Idea#show %>

<li class="media answer answer-<%= answer.id %> content-bg">

    <%= render partial: "evaluations/vote_wrapper", locals: {voteable: answer} %>


    <div class="media-body">
      <div class="media-body">
        <div class="media-item-body">
            <div class='userwrap'>
              <div class='photo'>
              <%= link_to (image_tag answer.user.profile.photo.thumb, :size => "36x36", class: 'img-rounded'), profile_path(answer.user.profile)%>
              </div>
              <div class='username'>
              <%= render answer.user %><br>
              <small><i> Posted <%= time_ago_in_words(answer.created_at) %> ago</i></small>
              </div>
            </div>
          <br>
          <p><%= answer.brief %></p>
          <hr style="color:#fff;background-color:#fff;border-color:#fff;" />
        </div>
      </div>
      <div class='pull-right'>
        <% if answer.question.idea.is_phase_1? %>
          <%= link_to "Add comment", 'javascript:void(0);', class: "add-answer-comment" %>
        <% else %>
          <span class="link-dis"> Add comment </span>
        <% end %>
        <% if answer.comments.count > 0 %>
          <span class="add-comment-bar link-dis"> | </span>
          <a href='javascript:void(0);' class='hideanscomments' style='display:none;'>Hide Answer Comments (<%= answer.comments.count %>)</a>
          <a href='javascript:void(0);' class='showanscomments'>Show Answer Comments (<%= answer.comments.count %>)</a>
        <% end %>
      </div>
      <br>
      <div class="media-body answercomments" style='display:none;'>
        <ul class="media-list comments answer-comments">
          <div class='white-bg comment-form' style='display:none;'>
            <%= render partial: 'comments/form', locals: { url: create_comment_path(commentable_id: answer.id, commentable_type: 'Answer', idea_id: answer.question.idea.id) } %><br>
            <%= link_to 'Cancel', 'javascript:void(0);', class: 'cancel-answer-comment' %>
          </div>
          <% if answer.comments.count > 0 %>
            <%= render vote_order(answer.comments.includes(:user)) %>
          <% end %>
        </ul>
      </div>
    </div>
</li>

app/views/answers/_form.html.erb
<%= form_for @answer, url: url do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label 'Answer' %><br>
    <%= f.text_area :brief, placeholder: 'READ THIS BEFORE TYPING IF THIS IS THE FIRST ANSWER YOU ARE SUBMITTING. Be as detailed as possible and try to back up your points with articles, multimedia, or other sources. Be friendly when making your points, but do not be afraid to disagree with other users; multiple viewpoints enhance discussion and accelerate development. Finally, keep in mind that the best answers are written with proper grammar and full sentences.', rows: 5, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Answer', :class => "btn btn-primary" %>
  </div>


<% end %>

app/views/answers/create.js.erb
$(".js-inline-form").replaceWith("<%= j render @answer %>");
idea_id = "<%= escape_javascript(@answer.question.idea.id.to_s) %>";
$(".idea-follow-form-" + idea_id).replaceWith("<%= escape_javascript(render('ideas/unfollow', idea: @answer.question.idea)) %>");
$("#newanswer").text("Add answer");
if($("div.no.answers").length > 0) {
	$("div.no.answers").remove()
}

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/new.js.erb
var selector = "ul.answers"
var y = $("a:contains('Cancel')").not("#newanswer")
if ($(y).closest(" .media.comment.comment").length > 0) {
	$(y).text("Reply to comment")
}
else {
	$(y).text("Add comment")
	$("div.no.comments").show()
}

if (!$(selector).children().hasClass("js-inline-form")) {
	$(" .js-inline-form").remove()
	$(selector)
		.append("<li class='js-inline-form'><%= j render :partial => 'answers/form' %></li>")
	$("#newanswer").text("Cancel")
	$("div.no.answers").hide()
}
else {
	$(" .js-inline-form").remove()
	$("#newanswer").text("Add answer")
	$("div.no.answers").show()
}

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brief:</strong>
  <%= @answer.brief %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', Idea.find(Question.find(@answer.question_id).idea_id) %>