config/routes.rb
StartIt::Application.routes.draw do

# =============================================================================
# Application Wide ============================================================
# =============================================================================
  root to: 'home#index'

  # User ======================================================================
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', 
                                    sessions: 'sessions', confirmations: 'confirmations' }
  devise_scope :user do
    get "users/sign_in", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "login", :to => "devise/sessions#new"
  end

  # Nav bar ===================================================================
  get 'create', to: 'explore#create'
  get 'build', to: 'explore#build'
  get 'buy', to: 'explore#buy'

  get 'terms', to: 'home#terms', as: 'terms'
  get 'privacy', to: 'home#privacy', as: 'privacy'  

# =============================================================================
# Phase 1 =====================================================================
# =============================================================================

  match "/comments/vote", via:[:post], as: "comment_vote"
  match "/questions/vote", via:[:post], as: "question_vote"
  match "/answers/vote", via:[:post], as: "answer_vote"
  match "/ideas/vote", via:[:post], as: "idea_vote"
  match "/solutions/vote", via:[:post], as: "solution_vote"
  
  get "evaluations/show"

  #get "/dashboard", to: 'home#dashboard', as: 'dashboard'

  resources :notifications, only: [:index, :destroy]
  resources :profiles, except: [:index, :new, :create]
  resources :idea_relationships, only: [:create, :destroy]
  resources :comments, only: [:show]
  resources :questions, except: [:index, :create, :update]
  resources :answers, except: [:index, :create]
  resources :aspects, except: [:index, :show, :create, :new] do
    resources :solutions, except: [:index, :edit, :update, :create, :show, :new]
  end

  resources :ideas do
    member do
      post :vote 
      get :followers
    end
    resources :idea_build, only: [:edit, :clear, :update] # This is phase 2
  end

  get '/solutions/:id', to: 'solutions#show', as: 'solution'
  post '/ideas/:idea_id/aspects/:id/solution/create', to: 'solutions#create', as: 'create_solution'

  get '/ideas/:id/questions/new', to: 'ideas#new_question', as: 'idea_new_question'
  get '/ideas/:id/questions/:question_id', to: 'ideas#edit_question', as: 'idea_edit_question'
  post '/ideas/:id/questions/', to: 'questions#create', as: 'create_question'
  patch '/ideas/:id/questions/:question_id', to: 'questions#update', as: 'update_question'
  post '/ideas/:id/questions/:question_id', to: 'answers#create', as: 'create_answer'
  post "/ideas/:idea_id/:commentable_type/:commentable_id", to: 'comments#create', as: 'create_comment'

  get '/ideas/:idea_id/aspects/:id', to: 'aspects#show', as: 'idea_aspect'

  get '/ideas/:id/define', to: 'ideas#define'
  get '/ideas/:id/reputation', to: 'ideas#reputation', as: 'reputation_path'
  get '/ideas/:id/activity', to: 'ideas#activity'

  get '/profiles/:id/skills', to: 'profiles#skills'
  get "profile", :to => "profiles#show"
  
  get "activities/index"
  get "/followed_ideas", to: 'home#followed_ideas', as: 'followed_ideas'

  post 'ideas/:id/increase_create_length', to: 'ideas#increase_create_length', as: 'increase_create_length'

# =============================================================================
# Phase 2 =====================================================================
# =============================================================================

=begin
  get 'build_needs_team', to: 'explore#needs_team'
  get 'documentation', to: 'home#documentation'

  get "/ideas/:idea_id/parts/:id/edit", to: "parts#edit", as: "edit_part"
  get "/ideas/:idea_id/parts/:id/help_content", to: "parts#help_content", as: "part_help_content"
  get '/download', to: 'parts#download', as: 'download'
  get "/ideas/:idea_id/parts/:id/admin_tasks", to: "parts#admin_tasks", as: "part_admin_tasks"
  put "/ideas/:idea_id/parts/:id/update", to: "parts#update", as: "update_part"
  put "/ideas/:idea_id/parts/:id/update_image", to: "parts#update_image", as: "update_image_part"
  put "/ideas/:idea_id/parts/:id/add_user_to_repo", to: "parts#add_user_to_repo", as: "add_user_to_repo"
  put "/ideas/:idea_id/parts/:id/unstart_part", to: "parts#unstart_part", as: "unstart_part"
  post "/ideas/:idea_id/parts/:id/update_status", to: "parts#update_status", as: "update_status"
  delete "/ideas/:idea_id/parts/:id/clear", to: "parts#clear", as: "clear_part"
  delete "/ideas/:idea_id/parts/:id/edit/remove_upload/:upload_id", to:"part_upload#destroy", as: "destroy_upload"
  delete "/ideas/:idea_id/parts/:id/remove_user", to: "parts#remove_user_from_repo", as: "remove_user_from_repo"
  
  get '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#new', as: 'new_admin_task'
  post '/ideas/:idea_id/parts/:part_id/admin_tasks/:id/update_status', to: 'admin_tasks#update_status', as: 'update_admin_task'
  post '/ideas/:idea_id/parts/:id/admin_tasks/new', to: 'admin_tasks#create', as: 'create_admin_task'

  post '/ideas/:idea_id/idea_build/:kind/:kind_id/comments/create', to: 'task_comments#create', as: 'create_task_comment'

  get "/ideas/:idea_id/build", to: "idea_builds#overview", as: 'idea_build'
  get "/ideas/:idea_id/overview/news_feed", to: 'idea_builds#news_feed', as: 'idea_build_feed'
  get "/ideas/:idea_id/overview/team_build", to: 'idea_builds#team_build', as: 'idea_build_team_build'
  get "/ideas/:idea_id/discussion", to: 'idea_builds#discussion', as: 'idea_build_discussion'
  post "/ideas/:idea_id/overview/news_feed/create_post", to: 'posts#create', as: 'create_post'
  post "/ideas/:idea_id/overview/team_build/create_proposal", to: 'posts#create_proposal', as: 'create_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/close_proposal", to: 'posts#close_proposal', as: 'close_proposal'
  post "/ideas/:idea_id/overview/team_build/:post_id/apply", to: 'team_applications#create', as: 'create_team_application'
  get "/ideas/:idea_id/overview/team_build/proposals/:post_id/", to: 'posts#show', as: 'post'
  get '/ideas/:idea_id/:kind/:kind_id/discussion', to: 'chats#new', as: 'new_chat'
  post '/ideas/:idea_id/:kind/:kind_id/create_chat', to: 'chats#create', as: 'create_chat'
  get '/ideas/:idea_id/:kind/:kind_id/chats', to: 'chats#index', as: 'chats'

  get "/ideas/:idea_id/build/components", to: "idea_builds#components", as: 'idea_build_components'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  post 'like/:model_name/:model_id/:user_id', to: 'likes#like', as: 'like'
  delete 'like/:model_name/:model_id/:user_id', to: 'likes#unlike', as: 'unlike'

  post '/strike/:user_id/:idea_build_id/:voter_id', to: 'strike#create', as: 'strike'  

  post '/ideas/:idea_build_id/team_applications/:team_application_id', to: 'team_memberships#create', as: 'create_team_member'

# =============================================================================
# Phase 3 =====================================================================
# =============================================================================

  post '/buy/:id/buy', to: 'buy_phase_vote#buy_vote', as: 'buy_vote'
  post '/buy/:id/use', to: 'buy_phase_vote#use_vote', as: 'use_vote'
=end

end

app/models/idea_build.rb
class IdeaBuild < ActiveRecord::Base
  belongs_to :idea
  has_one :plan_component, -> { includes(:parts) }
  has_one :business_plan_component, -> { includes(:parts) }
  has_one :prototype_component, -> { includes(:parts) }
  has_one :design_component, -> { includes(:parts) }
  has_many :team_memberships, -> { includes(:user) }
  has_many :posts, -> { includes(:user) }

  after_create :create_required_components

  def create_required_components
    create_component(PlanComponent)
    create_component(BusinessPlanComponent)
    create_component(DesignComponent)
    create_component(PrototypeComponent)
  end

  def no_progress?
    no_progress = 0
    no_progress += self.plan_component.get_progress
    no_progress += self.business_plan_component.get_progress
    no_progress += self.design_component.get_progress
    no_progress += self.prototype_component.get_progress
    
    no_progress == 0
  end

  private
    def create_component(component) 
      c               = component.new
      c.idea_build_id = self.id
      c.save
    end
end

app/controllers/idea_builds_controller.rb
class IdeaBuildsController < ApplicationController
  before_action :set_idea
  before_action :team_member, only: [:discussion, :overview, :components]
  before_action :set_idea_build
  before_action :summary_of_business, only: [:news_feed, :team_build]

  def overview
  end

  def components
  end

  def discussion
  end

  def news_feed
    @posts = get_posts('news')
    @post = Post.new
    @task_comment = TaskComment.new
  end 

  def team_build
    @posts = get_posts('team')
    @post = Post.new
    @task_comment = TaskComment.new
  end

  private 
    def set_idea
      @idea = Idea.find(params[:idea_id])
    end

    def set_idea_build
      @idea_build = @idea.idea_build
    end

    def get_posts(kind)
      @idea_build.posts.where(kind: kind)
    end

end

app/helpers/idea_build_helper.rb
module IdeaBuildHelper
end

app/views/idea_builds/_brief.html.erb
<div class='col-md-12 profile-border' style='margin-bottom:30px;'>
  <h1 class='set-font-bold' style="font-family:'Montserrat-Bold'">The Idea</h1>
  <hr>
  <p> <%= @brief.html_safe %> </p>
</div>
<hr>

app/views/idea_builds/_component.html.erb
<% (component.parts.sort_by {|p| p.name}).each do |part| %>
  <div class='row content-bg'>   
    <div class='col-md-8'>
      <% if part.name == 'Idea Description' %>
        <div style='float:left; height:40px; margin-right:5px; margin-left:-15px; display:none;' id='3-div'>
          <a id="3-pop-link" 
              href="#" 
              data-toggle="popover" 
              data-content="Each row is a part of a component. If a part's status is <b>unstarted</b> you may start it and submit the required content in exchange for <b>equity</b> in the idea and reputation points proportional to this equity. Each part carries a unique equity value, present on rightmost side of the row in green. Equity gaining is not a competition between team members; it is merely a way of quantifying team members' activity in the idea and making sure that all of you are contributing.<br><br>You do not need to have experience writing business plans or building prototypes; each part's edit page containers help content that tells you exactly what should be included in your contribution, including a structure you can follow. You can also find this information in the documentation section.<br><br>Once you finish the part, your team members will be able to review your content and leave you revision tasks to improve your work to gain more attention from investors!">
            <%= image_tag 'labthinghelp.png', size: '36x36', id: '3-img' %>
            <span id='3-close' class='pull-left' style='display:none; position:absolute; top:0px; margin-left:-5px; color:#34495E;'>
              <b>x</b>
            </span>
          </a>      
        </div>
      <% elsif part.name == 'Prototype' %>
        <div style='float:left; height:40px; margin-right:5px; margin-left:-15px; display:none;' id='6-div'>
          <a id="6-pop-link" 
              href="#" 
              data-toggle="popover" 
              data-content="The prototype component is the only one which varies according to the type of idea you submit. If the product is a physical good, you will need to build a CAD before the actual prototype itself. If the product is software-based, you will need to design the schema and write a flowchart instead of a CAD. For the prototype itself, in the former scenario you must build it out of wood/cardboard/other lightweight materials and record a video explaining its different features and how to use it. For the latter, the prototype will be purely code; your team will be added to the idea's <b>Bitbucket</b> account and you can begin pushing your code to that repository.<br><br>Although we encourage all members of Labthi.ng to try building every component and part regardless of their prior experience, the prototype component is one where prior experience and knowledge is recommended to ensure a high quality standard of product.">
            <%= image_tag 'labthinghelp.png', size: '36x36', id: '6-img' %>
            <span id='6-close' class='pull-left' style='display:none; position:absolute; top:0px; margin-left:-5px; color:#34495E;'>
              <b>x</b>
            </span>
          </a>      
        </div>
      <% elsif part.name == 'Market Analysis' %>
        <div style='float:left; height:40px; margin-right:5px; margin-left:-15px; display:none;' id='5-div'>
          <a id="5-pop-link" 
              href="#" 
              data-toggle="popover" 
              data-content="If there is a part that as a team you feel uncomfortable completing, may it be due to a lack of time, knowledge or experience, you can always write another proposal in the <b>overview - team build</b> section, detailing the exact expertise you seek, and hire another team member to complete this part.">
            <%= image_tag 'labthinghelp.png', size: '36x36', id: '5-img' %>
            <span id='5-close' class='pull-left' style='display:none; position:absolute; top:0px; margin-left:-5px; color:#34495E;'>
              <b>x</b>
            </span>
          </a>      
        </div>
      <% end %>
      <div style='float:left;'>
        <% if part.display_link?(current_user)%>
          <%= link_to part.name, part_help_content_path(id: part) %>
        <% end %>

        <br>   
        <%= "Status: " %>
        <h0 class='statustext'>
          <%= "#{part.status}"%>
        </h0>
      </div>
      <br>
    </div>

    <div class='col-md-4'>
      <div class='partstyle pull-right'>
        <div class='left'>
          <% if (part.name == 'Executive Summary' or 'Idea Description') and part.status != 'Accepted' %>
          <div style='float:left; margin-left:20px; height:35px; margin-top:6px;margin-right:4px;display:none;' id='4-div'>
            <a id="4-pop-link" 
                href="#" 
                data-toggle="popover" 
                data-content="The button I'm standing next to indicates whether or not you can take action, and what sort of action you can take. In general, blue buttons mean you can click on them and take action; grey buttons mean you cannot take action. If the button is blue and says <b>start</b>, it means you can start the part. After you do this, you will be the only user that can see click on the part and edit it. When you are finished, you can click the blue <b>finish</b> button. The button will then become grey and will say <b>finished</b>; now, you cannot click on the part to edit it because administrators and your team are reviewing your work and adding tasks for you to complete to improve it. When the button's text changes to <b>In Review</b> but stays grey, you can edit the part and complete the tasks to improve your work. Your team will vote to <b>accept</b> your part once they think the quality is of appropriate standard. <br><br>

                If the button is grey and says <b>locked</b> it means other parts must be completed before this part can be started (e.g. the <b>Executive Summary</b> part can only be started once all of the other business plan parts are completed). If it is grey and says <b>Unstarted</b>, you have already started a part and hence cannot start any others because you can only be in control of 1 part at once. Read more about how this works in the <b>documentation</b> section.">
              <%= image_tag 'labthinghelp.png', size: '36x36', id: '4-img' %>
              <span id='4-close' class='pull-left' style='display:none; position:absolute; top:5px; margin-left:-5px; color:#34495E;'>
                <b>x</b>
              </span>
            </a>      
          </div>
          <% end %>
          <% if part.locked_or_disabled?(current_user) %>
            <div style='float:right;'><%= button_to part.disabled_status, '', 
                :class => 'btn disabled btn-status', id: "#{part.id}"%></div>
          <% elsif part.display_button?(current_user) %>
            <div style='float:right;'><%= button_to part.button_status, update_status_path(id: part), 
                :class => 'btn btn-inverse', id: "#{part.id}"%></div>
          <% else %>
            <p class='pull-left left' align='right'>
               Author:<br>
              <%= link_to (part.user.name), profile_path(part.user.profile) %>             
            </p>
            <p class='pull-right'>
            <%= link_to (image_tag part.user.profile.photo.thumb, :size => "32x32"), profile_path(part.user.profile)%></p>
          <% end %>     
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/idea_builds/_progress.html.erb
<% if @idea_build.no_progress? %>
  <div class='row'>
    <div class='col-md-3 no-gutter'><img src='/images/alien.png' alt='alien' style='height:80px;'></div>
    <div class='col-md-9 no-gutter'>
      <p>The team has not made any progress in <b>phase 2</b> yet.</p>
      
    </div>
  </div><br>
<% else %>
  <p> 
    Plan Component: 
    <div class="progress" style='background-image:none; background-color:white;'>
      <div class="progress-bar" role="progressbar" aria-valuenow="<%= @idea_build.plan_component.get_progress %>" 
               aria-valuemin="0" aria-valuemax="100" style="width:<%= @idea_build.plan_component.get_progress %>%;color:<%= @idea_build.plan_component.get_color%>">
        <%= @idea_build.plan_component.get_progress %>%
      </div>
    </div> 
  </p>
  <p>
    Business Plan Component:
    <div class="progress" style='background-image:none;'>
      <div class="progress-bar" role="progressbar" aria-valuenow="<%= @idea_build.business_plan_component.get_progress %>" 
               aria-valuemin="0" aria-valuemax="100" style="width:<%= @idea_build.business_plan_component.get_progress %>%;color:<%= @idea_build.business_plan_component.get_color%>">
        <%= @idea_build.business_plan_component.get_progress %>%
      </div>
    </div> 
  </p>
  <p>
    Design Component:
    <div class="progress" style='background-image:none; background-color:white;'>
      <div class="progress-bar" role="progressbar" aria-valuenow="<%= @idea_build.design_component.get_progress %>" 
               aria-valuemin="0" aria-valuemax="100" style="width:<%= @idea_build.design_component.get_progress %>%;color:<%= @idea_build.design_component.get_color%>">
        <%= @idea_build.design_component.get_progress %>%
      </div>
    </div> 
  </p>
  <p> 
    Prototype Component:
    <div class="progress" style='background-image:none; background-color:white;'>
      <div class="progress-bar" role="progressbar" aria-valuenow="<%= @idea_build.prototype_component.get_progress %>" 
               aria-valuemin="0" aria-valuemax="100" style="width:<%= @idea_build.prototype_component.get_progress %>%;color:<%= @idea_build.prototype_component.get_color%>">
        <%= @idea_build.prototype_component.get_progress %>%
      </div>
    </div> 
  </p>
<% end %>

app/views/idea_builds/_secondary_nav.html.erb
<div class='col-md-12 no-gutter'>
  <%= render 'ideas/phase_2' %>
  <hr>
</div>

<div class="secondary_nav">
  <% if current_page?("/ideas/#{@idea.id}/build") %>
     <div style='float:left; height:40px; margin-right:5px; margin-left:-15px; display:none;' id='2-div'>
       <a id="2-pop-link" 
           href="#" 
           data-toggle="popover" 
           data-content="Visit the <b>overview</b> page to see information about your phase 2 progress, your brief and your current team members. The  <b>discussion</b> tab is a general live chat with your team; the chat is not limited to a specific component or even the idea itself. In the <b>news feed</b> tab of the overview, you can post updates about your progress as a team, market your idea, speak to your followers and more. Treat it almost like a Twitter or Facebook feed for your idea! In the <b>team build</b> tab, you can write proposals for obtaining new team members and read users' applications to your proposals.">
         <%= image_tag 'labthinghelp.png', size: '36x36', id: '2-img' %>
         <span id='2-close' class='pull-left' style='display:none; color:#34495E;'>
           <b>x</b>
         </span>
       </a>      
     </div>
    <% elsif current_page?("/ideas/#{@idea.id}/overview/news_feed") %>
     <div style='float:left; height:40px; margin-right:5px; margin-left:-15px;' id='1-div'>
       <a id="1-pop-link" 
           href="#" 
           data-toggle="popover" 
           data-content="The overview page of an idea in phase 2 is the content the labthi.ng community (non team members) will see. Here, you will find a brief pitch of the idea, detailing the problem the business solves, the different features of the product and business model and its goals and future direction. You will also find information about its phase 2 progress with respect to how many parts have been completed in each component. This will give investors and the community an idea about how diligent the team is, how quickly the idea is being built and can be ready for launch, and any problem areas that members of the community could help solve. Finally, you will find a list of the current team members building the idea, along with their equity and reputation stakes and a brief summary about themselves.<br><br>Scroll down to the second navbar to learn about the <b>news feed</b> section also present on this page.">
         <%= image_tag 'labthinghelp.png', size: '36x36', id: '1-img' %>
         <span id='1-close' class='pull-left' style='display:none; color:#34495E;'>
           <b>x</b>
         </span>
       </a>      
     </div>    
   <% end %>
  <div class="secondary-nav">
    <%= link_to "Overview", {
      controller: "idea_builds",
      action: "news_feed" },
      class: 'btn btn-default text ' + active_when(:controller => 'idea_builds', :action => 'news_feed')
    %>
    <%= link_to "Build", {
      controller: "idea_builds",
      action: "overview" },
      class: 'btn btn-default text ' + active_when(:controller => 'idea_builds', :action => 'overview')
    %>
    <%= link_to "Discussion", new_chat_path(idea_id: @idea.id, kind: 'idea_build', kind_id: @idea_build.id), 
      class: 'btn btn-default text ' + active_when(new_chat_path(idea_id: @idea.id, kind: 'idea_build', kind_id: @idea_build.id))
    %>
  </div>
</div>
<br><br>

app/views/idea_builds/_secondary_sub_nav.html.erb
<div class='col-md-12 no-gutter' style='margin-top:30px;'>
  <% if current_page?("/ideas/#{@idea.id}/overview/news_feed") %>
     <div style='float:left; height:40px; margin-right:5px; margin-left:-15px; display:none;' id='2-div'>
       <a id="2-pop-link" 
           href="#" 
           data-toggle="popover" 
           data-content="The news feed below resembles a Facebook/Twitter feed or blog consisting of posts made by the team detailing their progress through phase 2, information about the product or business, opportunities for the community to help them with promotional aspects or feedback, and general thoughts, opinions and news. Feel free to <b>comment</b> and <b>like</b> any of the content.<br><br>Click on the <b>team build</b> link to learn about how teams make proposals to obtain team members.">
         <%= image_tag 'labthinghelp.png', size: '36x36', id: '2-img' %>
         <span id='2-close' class='pull-left' style='display:none; color:#34495E;'>
           <b>x</b>
         </span>
       </a>      
     </div>
  <% elsif current_page?("/ideas/#{@idea.id}/overview/team_build") %>
     <div style='float:left; height:40px; margin-right:5px; margin-left:-15px;' id='1-div'>
       <a id="1-pop-link" 
           href="#" 
           data-toggle="popover" 
           data-content="This section consists of proposals made by different team members to the community regarding an open spot on the idea's team. Here, the team will post information about the current state of progress of the idea, a problem area or an area where more help is needed for the start-up to be built, and the qualities and skills of the team member the current team is looking to see in the applications. If you are interested in the idea and feel as though you could make a good contribution, submit an application to the proposal and explain why you would be a good team member. Your idea building skills (e.g. business plan, idea planning, prototyping and designing) displayed on your profile, along with a summary of your contributions (if any) in phase 1 to the idea's brainstorm will be listed along with your application. Try and pitch yourself to the team in a similar way to how they pitched the idea. To read more about this process, visit the <b>documentation</b> section.">
         <%= image_tag 'labthinghelp.png', size: '36x36', id: '1-img' %>
         <span id='1-close' class='pull-left' style='display:none; color:#34495E;'>
           <b>x</b>
         </span>
       </a>      
     </div>
  <% end %>
  <div class="secondary_nav">
    <div class="secondary-nav">
      <%= link_to "News Feed", {
        controller: "idea_builds",
        action: "news_feed" },
        class: 'btn btn-default text ' + active_when(:controller => 'idea_builds', :action => 'news_feed')
      %>
      <%= link_to "Team Building", {
        controller: "idea_builds",
        action: "team_build" },
        class: 'btn btn-default text ' + active_when(:controller => 'idea_builds', :action => 'team_build')
      %>
    </div>
  </div>  
</div>

app/views/idea_builds/_sidebar.html.erb
<div class='col-md-12 profile-border'>
  <h3 class='set-font-bold'>Progress</h2>
  <hr>
  <%= render 'idea_builds/progress' %>
</div><br>
<div class='col-md-12 profile-border'>
  <h3 class='set-font-bold'>The Team</h3>
 <hr>
  <div class="idea-followers">
    <% @users_points.each do |user, points| %>
      <%= render 'users/team_member', user: user, points: points %>
    <% end %>
  </div>
</div>

app/views/idea_builds/discussion.html.erb
<%= render 'secondary_nav' %>

<%= link_to 'Discussion', new_chat_path(idea_id: @idea.id, kind: 'idea_build', kind_id: @idea_build.id) %>

app/views/idea_builds/news_feed.html.erb
<%= render 'idea_builds/secondary_nav' %>
<div class='col-md-8 no-gutter'>
  <%= render 'idea_builds/brief' %>
  <br>
  <div class='row no-gutter'>
    <div class='welcome-block clearfix'>
      <h3 class='set-font pull-left' style='display:inline;'>News Feed</h3>
      <button href='javascript:void(0);' class='btn btn-info pull-right' style='margin-right:13px;padding-left:9px;margin-top:13px;' id='newpost'>Create Post</button>
    </div>
    <div class='content-bg' style='display:none;' id='posts'>
      <%= render partial: 'posts/form', locals: { url: create_post_path, placeholder: 'Update the Labthi.ng community on how the process of building your start-up is going!', title: 'New Post' } %><br>
      <%= link_to 'Cancel', 'javascript:void(0);', id: 'cancel' %>
    </div>
    <ul class="posts media-list">
      <% if @posts.count > 0 %>
        <%= render (@posts.sort_by {|p| p.created_at}).reverse %>
      <% else %>
      <div class='content-bg no posts' id='noposts'>
        There are no posts yet. Why don't you add one?
      </div>
      <% end %>
    </ul>
  </div>
</div>
<div class='col-md-4'>
  <%= render 'idea_builds/sidebar' %>
</div>

app/views/idea_builds/overview.html.erb
<%= render 'secondary_nav' %>
    <div class='col-md-12 componentstyle'>
      <a href='javascript:void(0);' id='planlink'>
        <h4><strong>Plan Component</strong></h4>
      </a>
      <div id='plan'><%= render 'component', 
          component: @idea_build.plan_component %></div>
    </div>
  <br>

    <div class='col-md-12 componentstyle'>
      <a href='javascript:void(0);' id='bplink'>
        <h4><strong>Business Plan Component</strong></h4>
      </a>
      <div id='bp'><%= render 'component', 
          component: @idea_build.business_plan_component %></div>
    </div>
  <br>

    <div class='col-md-12 componentstyle'>
      <a href='javascript:void(0);' id='prototypelink'>
        <h4><strong>Prototype Component</strong></h4>
      </a>
      <div id='prototype'><%= render 'component', 
          component: @idea_build.prototype_component %></div>
    </div>
  <br>

    <div class='col-md-12 componentstyle'>
      <a href='javascript:void(0);' id='designlink'>
        <h4><strong>Design Component</strong></h4>
      </a>
      <div id='design'><%= render 'component', 
          component: @idea_build.design_component %></div>
    </div>
  <br>

app/views/idea_builds/team_build.html.erb
<%= render 'idea_builds/secondary_nav' %>
<div class='col-md-8 no-gutter'>
  <%= render 'idea_builds/brief' %>
  <%= render 'idea_builds/secondary_sub_nav', locals: { url: 'btn btn-default text ' + active_when(idea_build_team_build_path) } %>
  <br>
  <div class='row no-gutter'>
    <div class='welcome-block clearfix'>
      <h3 class='pull-left'>Team Build</h3>
      <button href='javascript:void(0);' class='btn btn-info pull-right' style='width:114px;margin-right:13px;padding-left:9px;margin-top:13px;' align='center' id='newpost'>Create Proposal</button>
    </div>
    <div class='content-bg' style='display:none;' id='posts'>
      <%= render partial: 'posts/form', locals: { url: create_proposal_path, placeholder: 'Write a proposal to gain team members for your start-up. Explain what you hope to achieve with your team members, the skills you have to offer, and the skills you hope they can contribute to the start-up. You should also tell the community a bit about yourself, how you like to work, and in how long you hope to finish building the start-up.', title: 'New Proposal' } %><br>
      <%= link_to 'Cancel', 'javascript:void(0);', id: 'cancel' %>
    </div>
    <ul class="posts media-list">
      <% if @posts.count > 0 %>
        <%= render (@posts.sort_by {|p| p.created_at}).reverse %>
      <% else %>
        <div class='content-bg no posts' id='noposts'>
          There are no proposals yet. Why don't you add one to get your team started?
        </div>
      <% end %>
    </ul>
    <br><br><hr>
  </div>
</div>
<div class='col-md-4'>
  <%= render 'idea_builds/sidebar' %>
</div>